name: Get latest release branch

outputs:
  branch-name:
    description: The name of the release branch, with
    value: ${{ steps.get-latest-release-branch.outputs.branch-name }}
  branch-version:
    description:
    value: ${{ steps.get-latest-release-branch.outputs.branch-version }}

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v6
      id: get-latest-release-branch
      with:
        result-encoding: string
        script: |
          const releaseBranches = await github.rest.git.listMatchingRefs({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "heads/release-x.",
          });

          const getVersionFromBranch = branch => {
            const match = branch.match(/release-x\.(.*?)\.x$/);
            return match && parseInt(match[1]);
          };
          const latestReleaseBranch = releaseBranches.data
            .filter(branch => getVersionFromBranch(branch.ref) !== null)
            .reduce(
              (prev, current) =>
                getVersionFromBranch(prev.ref) > getVersionFromBranch(current.ref)
                  ? prev
                  : current,
              { ref: "" },
            );
          const latestReleaseBranchName = latestReleaseBranch.ref.replace(
            /^refs\/heads\//,
            "",
          );

          console.log(`Latest release branch: ${latestReleaseBranchName}`);

          const latestReleaseBranchVersion = parseInt(latestReleaseBranchName.split('.')[1]);
          
          console.log(`Latest major release version: ${latestReleaseBranchVersion}`);
          
          const branchName = context.ref.split('/').pop();
          console.log(`Current Branch: ${branchName}`);
          
          return {
            'branch-name': latestReleaseBranchName,
            'branch-version': latestReleaseBranchVersion,
          };
