name: Set Github Required for Status Check

runs:
  using: "composite"
  steps:
    - name: Log
      run: echo ${{ github.event.head }}
      shell: bash
    - name: Set required status check
      run: gh api "repos/metabase/metabase/statuses/${{ github.event.head }}" -f context="validate" -f state="pending"
      shell: bash
