name: Set Github Required for Status Check

runs:
  using: "composite"
  steps:
    - name: Get SHA1 commit
      id: vars
      run: echo "::set-output name=sha::$(git rev-parse $GITHUB_SHA)"
      shell: bash
    - name: Set required status check
      run: gh api "repos/metabase/metabase/statuses/$sha" -f context="validate" -f state="pending"
      shell: bash
