name: Set Github Required for Status Check

runs:
  using: "composite"
  steps:
    - name: Log
      run: echo $HEAD
      shell: bash
    - name: Set required status check
      run: gh api "repos/metabase/metabase/statuses/$HEAD" -f context="validate" -f state="pending"
      shell: bash
