name: Set Github Required for Status Check

runs:
  using: "composite"
  steps:
    - name: Set required status check
      run: gh api repos/metabase/metabase/statuses/${{ github.event.pull_request.head.sha }} -f context="validate" -f state="pending"
      env:
        GITHUB_TOKEN: ${{ GITHUB_TOKEN }}
      shell: bash
