name: Set Github Required for Status Check

runs:
  using: "composite"
  steps:
    - name: Set required status check
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh api repos/metabase/metabase/statuses/${{ github.event.pull_request.head.sha }} -f context="validate" -f state="pending"
      shell: bash
