name: Prepare node environment
runs:
  using: "composite"
  steps:
    - name: Prepare Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'yarn'
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
    - run: yarn install --frozen-lockfile --prefer-offline
      shell: bash
