name: Prepare Cypress
runs:
  using: "composite"
  steps:
    - name: Prepare Node environment
      uses: ./.github/actions/prepare-node

    - name: Get Cypress cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/Cypress
        key: ${{ runner.os }}-Cypress-${{ hashFiles('**/yarn.lock') }}
        
    - name: Ensure that Cypress executable is ready
      run: |
        yarn cypress install
        yarn cypress cache path
        yarn cypress cache list
        yarn cypress verify
