name: Prepare front-end environment
runs:
  using: "composite"
  steps:
    - name: Prepare Node environment
      uses: ./.github/actions/prepare-node
      
    - name: Get M2 cache
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-cljs-${{ hashFiles('**/shadow-cljs.edn') }}
