name: Driver Tests

on:
  push:
    branches:
      - flaky-redshift

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

jobs:

  be-tests-redshift-ee:
    if: ${{ always() }}
    runs-on: ubuntu-22.04
    timeout-minutes: 90
    env:
      CI: 'true'
      DRIVERS: redshift
      MB_REDSHIFT_TEST_USER: metabase_ci
      MB_REDSHIFT_TEST_DB: testdb
      MB_REDSHIFT_TEST_HOST: ${{ secrets.MB_REDSHIFT_TEST_HOST }}
      MB_REDSHIFT_TEST_PASSWORD: ${{ secrets.MB_REDSHIFT_TEST_PASSWORD }}
    steps:
    - uses: actions/checkout@v4
    - name: Test Redshift driver
      uses: ./.github/actions/test-driver
      with:
        junit-name: 'be-tests-redshift-ee'
        test-args: ":exclude-tags '[:mb/once]'"
