# Triggers Percy job on push to master and release branches to create baseline screenshots
name: Percy

on:
  workflow_run:
    workflows: [Uberjar]
    types: [completed]
    branches: [master, release**]
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "**unit.spec.js"
      - "frontend/test/**"
      - "!frontend/test/metabase-visual/**"

  percy:
    timeout-minutes: 30
    runs-on: buildjet-8vcpu-ubuntu-2004
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Prepare JRE (Java Run-time Environment)
        uses: actions/setup-java@v1
          with:
            java-package: jre
            java-version: 8
      - run: java -version
      - name: Prepare front-end environment
        uses: ./.github/actions/prepare-frontend
      - name: Prepare cypress environment
        uses: ./.github/actions/prepare-cypress
      - uses: actions/download-artifact@v2
        name: Retrieve uberjar artifact
        with:
          name: metabase-oss-uberjar
      - name: Get the version info
        run: |
          jar xf target/uberjar/metabase.jar version.properties
          mv version.properties resources/
      - name: Run maildev
        run: docker run -d -p 80:80 -p 25:25 maildev/maildev
      - name: Launch uberjar
        run: java -jar ./target/uberjar/metabase.jar &
      - name: Wait for Metabase to start
        run: while ! curl -s 'http://localhost:3000/api/health' | grep '{"status":"ok"}'; do sleep 1; done
      - name: Percy Test
        run: yarn run test-visual-no-build
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        if: env.PERCY_TOKEN != null
