name: Source dependency analysis

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    paths:
    - 'frontend/**'
    - 'shared/**'
    - 'enterprise/frontend/**'
    - '**/package.json'
    - '**/yarn.lock'
    - '**/.eslintrc'
    - '.github/workflows/**'

jobs:

  analyze-deps:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2

    - name: Prepare Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Get yarn cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
    - run: yarn install --frozen-lockfile --prefer-offline

    - name: Get the base branch
      run: git fetch origin master

    - name: List changed source files
      run: git diff origin/master..HEAD --name-only

    - name: Find other source files potentially affected directly
      run: git diff origin/master..HEAD --name-only | node frontend/parse-deps.js filter-dependents

    - name: Find ALL other source files potentially affected INdirectly
      run: git diff origin/master..HEAD --name-only | node frontend/parse-deps.js filter-all-dependents
