name: Build Uberjar

on:
  push:

jobs:
  build:
    name: Build Metabase for ${{ matrix.edition }}
    runs-on: ubuntu-20.04
    timeout-minutes: 40
    strategy:
      matrix:
        edition: [ee, oss]
    env:
      MB_EDITION: ${{ matrix.edition }}
      INTERACTIVE: false
      GITHUB_TOKEN: "${{ github.token }}"
    steps:
    - name: Check out the code
      uses: actions/checkout@v3
    - name: Set required status check
      env:
       GITHUB_TOKEN: "${{ github.token }}"
      run: gh api "repos/metabase/metabase/statuses/${{ github.event.pull_request.head.sha }}" \
        -f context="validate" \
        -f state="pending"
    - name: Prepare front-end environment
      uses: ./.github/actions/prepare-frontend
    - name: Prepare back-end environment
      uses: ./.github/actions/prepare-backend
    - name: Build
      run: ./bin/build
    - name: Prepare uberjar artifact
      uses: ./.github/actions/prepare-uberjar-artifact
    - name: Update required status check
      env:
       GITHUB_TOKEN: "${{ github.token }}"
      run: gh api "repos/metabase/metabase/statuses/${{ github.event.pull_request.head.sha }}" \
        -f context="validate" \
        -f state="success"
